### PR TITLE
updates for version 1.0.4

### PR DESCRIPTION
**Pull request by pmuellr**
@srl295 Should probably be in the habit of having someone review version updates - could you take a look?

Should have also had you look at the PR that makes up the functional change for this version - PR https://github.com/cloudfoundry-community/node-cfenv/pull/22 - could you peek at that as well?

I'll update npm after merging this.

### CODE REVIEW

**Comment by pmuellr** [comment]
@srl295 did you get a chance to review this?  Specifically the PR referenced in the initial comment.

**Comment by pmuellr** [comment]
went ahead and merged this and then published to npm as 1.0.4

**Comment by srl295** [comment]
sorry, i did not see this at all until the 'went ahead and merged' :(

**Comment by srl295** [comment]
after the fact LGTM

**Pull request merged**
